Allow to change the way the images are being downloaded
spatie/laravel-medialibrary pull request #2054
Opened 2020-09-20 09:53 UTC by chrysanthos

We have a case were the images cannot be downloaded using `fopen` but instead a client should be used. With this changes we will be able to change how the image is downloaded and instead use either curl (with additional headers) or something else.

Let me know if you want me to add an interface there.

2020-09-21 07:53 UTC, freekmurze requested changes
Could you also add a tests and update the docs with an example of the new functionality.

2020-09-21 07:53 UTC, freekmurze commented on src/Downloaders/DefaultDownloader.php
> +    public function getTempFile($url)
Add a typehint and return type hint here

2020-09-21 07:53 UTC, freekmurze commented on config/media-library.php
> +    'media_downloader' => Spatie\MediaLibrary\Downloaders\DefaultDownloader::class,
I don't think this functionality warrants at place this high in the config file. Let's move this to the bottom.

2020-09-21 13:46 UTC, chrysanthos commented
Thanks for the review @freekmurze. I made the fixes and added the docs. 

It seems like there are a lot of tests that already cover the whole method [here](https://github.com/spatie/laravel-medialibrary/blob/master/tests/Feature/FileAdder/IntegrationTest.php#L298-L319) and [here](https://github.com/spatie/laravel-medialibrary/blob/master/tests/Feature/FileAdder/IntegrationTest.php#L346-L392). Let me know if there is special case which is not handled and you want tested.

2020-09-22 06:42 UTC, freekmurze requested changes

2020-09-22 06:42 UTC, freekmurze commented on src/Downloaders/DefaultDownloader.php
> +class DefaultDownloader
Let's make this class implement an `Downloader` interface with that `getTempFile` method in it. In the readme and config file it should be mentioned. That a valid downloader is any class that implements that new interface.

2020-09-30 14:32 UTC, chrysanthos commented
Hey @freekmurze, does this seem ready to be merged or do you have any more changes you'd like to see?

2020-09-30 14:45 UTC, freekmurze commented
I need to find some time to review this.

2020-09-30 21:23 UTC, merged

2020-09-30 21:23 UTC, freekmurze commented
Thanks!