Allow customization of the file name of a Media when adding it to a zip
spatie/laravel-medialibrary pull request #2176
Opened 2020-11-13 13:02 UTC by Arkhas

Currently you can only specify the sub folder when adding a file to a zip.

I would allow the customization of the file name while doing it by adding a custom property : 

`zip_filename_suffix`

Update in the documentation : 

https://github.com/spatie/laravel-medialibrary/pull/2175

2020-11-13 14:04 UTC, freekmurze commented
Thanks for this, but I'm not going to merge this in. This PR brings some extra complexity that I'd not willing to take on for now.

2020-11-13 15:01 UTC, Arkhas commented
Then how can I customize a filename when adding it to a zip when the file is coming from S3 ? 

Right now, when zipping files coming from S3, you just get a messy folder with all file with random names instead of the `name` attribute.

A less complex solution would be to directly use the 'name' of the file but it may be a breaking change when adding file to a zip, what do you think ?

2020-11-13 15:07 UTC, Arkhas commented
I can also make this part : 

```
protected function getZipFileNameWithoutExtension(Collection $mediaItems, int $currentIndex): string
{
        return $mediaItems[$currentIndex]->hasCustomProperty('zip_filename_suffix') ? $mediaItems[$currentIndex]->getCustomProperty('zip_filename_suffix') : pathinfo($mediaItems[$currentIndex]->file_name, PATHINFO_FILENAME);
}
```

more simple like this : 

```
protected function getZipFileNameWithoutExtension(Collection $mediaItems, int $currentIndex): string
{
        return $mediaItems[$currentIndex]->zip_file_name ?: pathinfo($mediaItems[$currentIndex]->file_name, PATHINFO_FILENAME);
}
```

and the only thing to do is adding a getter to your Media model : 

```
public function getZipFileNameAttribute()
{
        return 'bar';
}
```

2021-01-17 14:51 UTC, freekmurze requested changes

2021-01-17 14:51 UTC, freekmurze commented on src/Support/MediaStream.php
> +        'fileNameInZip' => $this->getZipFileNamePrefix($this->mediaItems, $mediaItemIndex) . $this->getFileNameWithSuffix($this->mediaItems, $mediaItemIndex),
Could you make sure that there are no code style changes in this PR. Unnecessary changes like his make the PR harder to review.

2021-03-07 18:41 UTC, freekmurze commented
Closing due to inactivity.

2021-03-07 18:41 UTC, closed without merging