Add simpler way to prefix the root directory where media are saved
spatie/laravel-medialibrary pull request #2576
Opened 2021-09-04 06:11 UTC by kevinpurwito

Currently, if we use S3 bucket for our media, the `DefaultPathGenerator` will save all our media in the root directory of the S3 bucket. 

For example:
```
your-bucket
___1
______filename.png
___2
______filename.png
```

If we want to add a prefix/root directory where we want to save all our media, we need to implement our own `PathGenerator`.

For example:
```
your-bucket
___media
______1
_________filename.png
______2
_________filename.png
```

This PR made it simpler (IMO) to add this prefix, by simply using a new env `MEDIA_PREFIX`, which defaults to empty so that it doesn't change any existing behavior at all. 

This way, the general users who want to add their own root directory to store the media - such as myself, can easily do so without implementing our own `PathGenerator`.

2021-09-05 19:28 UTC, freekmurze commented
Seems nice! Thanks! 

Could you add a test that proves that this works?

2021-09-06 02:10 UTC, kevinpurwito commented
OK, I'll add a test later today or tomorrow.

2021-09-06 04:43 UTC, kevinpurwito commented
Hi, I've added the tests to make sure it works properly. 

Also, since I'm developing in Windows, I took the liberty to make the tests in `GetPathTest.php` to be Windows-friendly as well (I hope you don't mind).

![image](https://user-images.githubusercontent.com/11625012/132161526-127abbfa-0429-4072-abbb-17ff67a518a4.png)

2021-10-01 06:53 UTC, freekmurze requested changes

2021-10-01 13:58 UTC, kevinpurwito commented
Noted. I'll update later as you suggested.

2021-10-04 02:39 UTC, kevinpurwito commented
Hello, I've made the changes you suggested. Thank you for your kind review.

2021-10-04 06:30 UTC, freekmurze requested changes
Looks good, just a few nitpicks left

2021-10-04 06:30 UTC, freekmurze commented on tests/TestCase.php
> +    protected function makePathOsSafe($path)
Add parameter type hint + return type hint here

2021-10-04 06:30 UTC, freekmurze commented on .gitignore
> +.idea
Remove this, it belongs in a global gitignore

2021-10-04 06:30 UTC, freekmurze commented on config/media-library.php
> +    /*
Move this option to the bottom of the config file.

2021-10-04 07:32 UTC, kevinpurwito commented
> Looks good, just a few nitpicks left

Hi, I've made the changes you requested

2021-10-04 15:37 UTC, merged

2021-10-04 15:37 UTC, freekmurze commented
Thanks!