[V9] Remove regex on FileNamer
spatie/laravel-medialibrary pull request #2587
Opened 2021-09-14 14:42 UTC by erikn69

Closes #2586

2021-09-14 15:11 UTC, francoism90 commented
@erikn69 I'm not an expert, why has the change been made? Doesn't Laravel/Symfony offer any solution?

I would simple use a sanitize helper and/or replace all the illegal symbols with `-`.

2021-10-01 06:51 UTC, freekmurze requested changes

2021-10-01 06:51 UTC, freekmurze commented on src/Support/FileNamer/FileNamer.php
> +        $ext_length = strlen(pathinfo($fileName, PATHINFO_EXTENSION));
Variables are camel cased in all our packages.

2021-10-01 06:51 UTC, freekmurze commented on src/Support/FileNamer/FileNamer.php
> +        return substr($fileName, 0, strlen($fileName) - ($ext_length ? $ext_length + 1 : 0));
To me `strlen($fileName) - ($ext_length ? $ext_length + 1 : 0` is not very readable. Maybe put it the result a new variable with a meaningful name?

2021-10-01 06:51 UTC, freekmurze commented on tests/Feature/FileAdder/IntegrationTest.php
> +            ->usingFileName('other/[0]-{0}-(0)-otherFile.Name.jpg')
Please do not change the old test, but add a new one.

2021-10-01 14:10 UTC, erikn69 commented
@freekmurze fixed

2021-10-02 22:40 UTC, merged

2021-10-02 22:40 UTC, freekmurze commented
Thanks!