Add 'toInlineResponse' to Media
spatie/laravel-medialibrary pull request #2636
Opened 2021-10-20 09:20 UTC by mbardelmeijer

Follow-up of #1358

2021-11-14 07:09 UTC, rcerljenko commented
@mbardelmeijer @freekmurze  would be great if you can optionally pass a `conversion` name to these functions. eg:
```php
return $media->toResponse($request, 'thumb');
```

and how about responsive images?

2021-11-15 07:48 UTC, freekmurze requested changes

2021-11-15 07:48 UTC, freekmurze commented on docs/advanced-usage/outputting-media.md
> +```bash
This should be ```php I guess

2021-11-15 07:49 UTC, freekmurze commented
> would be great if you can optionally pass a conversion name to these function

Good idea!, could you take care of this @mbardelmeijer 

Responsive images are out of scope for now.

2021-11-15 09:09 UTC, mbardelmeijer commented
@freekmurze @rcerljenko I've checked if it would be possible to add conversion support to these methods, but ran into that the `stream` method from the `Filesystem` doesn't support passing a conversion name. 

We can get the file via the default methods, but then we don't have the memory optimized stream function to use.

We can add a 'getConversionStream' method for instance in the `Filesystem`, and a `conversionStream` to the Media object, but I do think this would grow the scope of the PR too much. Thoughts?

2021-11-15 11:08 UTC, rcerljenko commented
@mbardelmeijer yes it adds more work.. let @freekmurze decides

2021-11-17 09:36 UTC, merged

2021-11-17 09:36 UTC, freekmurze commented
Let's keep it simple for now.

Thanks @mbardelmeijer