Do not limit the maximum execution time if the queue connection is "sync"
spatie/laravel-medialibrary pull request #3618
Opened 2024-05-22 13:16 UTC by VGirol

When regenerating the conversions and if the queue connection is set to "sync", the jobs are not handled "asynchronously". So the execution time can be very long depending on the number of medias to handle. And in some cases, the script reached the maximum execution time defined in php.ini and exit with an error code.

This PR disable the maximum execution time if the queue connection is "sync".

2024-05-22 13:30 UTC, freekmurze requested changes
Thanks!

Could you remove all code style changes?

2024-05-22 13:30 UTC, freekmurze commented on src/Conversions/Commands/RegenerateCommand.php
> +        if (config('media-library.queue_connection_name') == 'sync') {
could you make this a strict check?

2024-05-22 16:39 UTC, VGirol commented on src/Conversions/Commands/RegenerateCommand.php
> +        if (config('media-library.queue_connection_name') == 'sync') {
Done

2024-05-22 16:40 UTC, VGirol commented
> Thanks!
> 
> Could you remove all code style changes?

I'm sorry. I didn't see that code style had changed.

2024-05-23 08:10 UTC, merged

2024-05-23 08:11 UTC, freekmurze commented
Thank you!